# Generated by Django 6.0.2 on 2026-02-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_ulr',
            new_name='image_url',
        ),
    ]
