# Generated by Django 6.0.2 on 2026-02-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_rename_image_ulr_post_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500, verbose_name='URL фото')),
            ],
        ),
    ]
